// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uxD-cJqDCFd8bErBpzlNw2Nc45kzQF4',
    appId: '1:1000618431420:web:a0f7fe45ad72dae7bd91b9',
    messagingSenderId: '1000618431420',
    projectId: 'clashup-b7a84',
    authDomain: 'clashup-b7a84.firebaseapp.com',
    storageBucket: 'clashup-b7a84.firebasestorage.app',
    measurementId: 'G-WW0LQRQ9LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ebcY4d1EwPt1pIxVTMYCJTXa4Chu2jM',
    appId: '1:1000618431420:android:c8c0ac04d68463c5bd91b9',
    messagingSenderId: '1000618431420',
    projectId: 'clashup-b7a84',
    storageBucket: 'clashup-b7a84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbsdnRmqHATlRUBgIoGAfmRRaB0YdjJpM',
    appId: '1:1000618431420:ios:6872b856e25e12b1bd91b9',
    messagingSenderId: '1000618431420',
    projectId: 'clashup-b7a84',
    storageBucket: 'clashup-b7a84.firebasestorage.app',
    iosBundleId: 'com.barreto.dev.clashup',
  );
}
